In [32]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [33]:


client = MongoClient("mongodb://root:rootpass@localhost:27017") # pyright: ignore[reportUndefinedVariable]
print(client.server_info()['version'])

8.2.6

In [34]:
db = client['clinica_veterinaria']
colecao = db['atendimentos']

In [35]:
atendimentos = [
    {"tutor": "Ana Lima", "animal": "Rex", "especie": "Cão", "servico": "Consulta", "valor": 120.0, "cidade": "Ourinhos", "data": datetime(2026, 1, 3), "forma_pagamento": "Pix"},
    {"tutor": "Bruno Souza", "animal": "Mimi", "especie": "Gato", "servico": "Vacina", "valor": 85.0, "cidade": "Assis", "data": datetime(2026, 1, 4), "forma_pagamento": "Cartão"},
    {"tutor": "Carla Nunes", "animal": "Thor", "especie": "Cão", "servico": "Banho e Tosa", "valor": 70.0, "cidade": "Marília", "data": datetime(2026, 1, 5), "forma_pagamento": "Dinheiro"},
    {"tutor": "Daniel Rocha", "animal": "Luna", "especie": "Gato", "servico": "Cirurgia", "valor": 450.0, "cidade": "Pompeia", "data": datetime(2026, 1, 6), "forma_pagamento": "Cartão"},
    {"tutor": "Elaine Costa", "animal": "Bolt", "especie": "Cão", "servico": "Consulta", "valor": 130.0, "cidade": "Ourinhos", "data": datetime(2026, 1, 7), "forma_pagamento": "Pix"},
    {"tutor": "Fabio Alves", "animal": "Nina", "especie": "Coelho", "servico": "Vacina", "valor": 95.0, "cidade": "Assis", "data": datetime(2026, 1, 8), "forma_pagamento": "Dinheiro"},
    {"tutor": "Gabriela Ferreira", "animal": "Max", "especie": "Cão", "servico": "Cirurgia", "valor": 520.0, "cidade": "Marília", "data": datetime(2026, 1, 9), "forma_pagamento": "Cartão"},
    {"tutor": "Henrique Lima", "animal": "Bela", "especie": "Gato", "servico": "Banho e Tosa", "valor": 60.0, "cidade": "Pompeia", "data": datetime(2026, 1, 10), "forma_pagamento": "Pix"},
    {"tutor": "Isabela Martins", "animal": "Duke", "especie": "Cão", "servico": "Consulta", "valor": 110.0, "cidade": "Ourinhos", "data": datetime(2026, 1, 11), "forma_pagamento": "Cartão"},
    {"tutor": "João Pereira", "animal": "Mel", "especie": "Gato", "servico": "Vacina", "valor": 90.0, "cidade": "Assis", "data": datetime(2026, 1, 12), "forma_pagamento": "Pix"},
    {"tutor": "Karen Souza", "animal": "Spike", "especie": "Cão", "servico": "Cirurgia", "valor": 480.0, "cidade": "Marília", "data": datetime(2026, 1, 13), "forma_pagamento": "Cartão"},
    {"tutor": "Lucas Oliveira", "animal": "Lola", "especie": "Gato", "servico": "Banho e Tosa", "valor": 65.0, "cidade": "Pompeia", "data": datetime(2026, 1, 14), "forma_pagamento": "Dinheiro"},
    {"tutor": "Marina Campos", "animal": "Rocky", "especie": "Cão", "servico": "Consulta", "valor": 125.0, "cidade": "Ourinhos", "data": datetime(2026, 1, 15), "forma_pagamento": "Pix"},
    {"tutor": "Nelson Araújo", "animal": "Kika", "especie": "Coelho", "servico": "Vacina", "valor": 80.0, "cidade": "Assis", "data": datetime(2026, 1, 16), "forma_pagamento": "Cartão"},
    {"tutor": "Olivia Santos", "animal": "Zeus", "especie": "Cão", "servico": "Cirurgia", "valor": 600.0, "cidade": "Marília", "data": datetime(2026, 1, 17), "forma_pagamento": "Cartão"},
    {"tutor": "Paulo Gomes", "animal": "Fifi", "especie": "Gato", "servico": "Banho e Tosa", "valor": 55.0, "cidade": "Pompeia", "data": datetime(2026, 1, 18), "forma_pagamento": "Dinheiro"},
    {"tutor": "Quésia Ramos", "animal": "Bob", "especie": "Cão", "servico": "Consulta", "valor": 115.0, "cidade": "Ourinhos", "data": datetime(2026, 1, 19), "forma_pagamento": "Pix"},
    {"tutor": "Rafael Torres", "animal": "Princesa", "especie": "Gato", "servico": "Vacina", "valor": 88.0, "cidade": "Assis", "data": datetime(2026, 1, 20), "forma_pagamento": "Cartão"},
    {"tutor": "Sandra Melo", "animal": "Toby", "especie": "Cão", "servico": "Cirurgia", "valor": 390.0, "cidade": "Marília", "data": datetime(2026, 1, 21), "forma_pagamento": "Cartão"},
    {"tutor": "Tiago Barros", "animal": "Fofinha", "especie": "Coelho", "servico": "Banho e Tosa", "valor": 50.0, "cidade": "Pompeia", "data": datetime(2026, 1, 22), "forma_pagamento": "Dinheiro"},
    {"tutor": "Ursula Freitas", "animal": "Branco", "especie": "Cão", "servico": "Consulta", "valor": 140.0, "cidade": "Ourinhos", "data": datetime(2026, 1, 23), "forma_pagamento": "Cartão"},
    {"tutor": "Vitor Cardoso", "animal": "Lilica", "especie": "Gato", "servico": "Vacina", "valor": 92.0, "cidade": "Assis", "data": datetime(2026, 1, 24), "forma_pagamento": "Pix"},
    {"tutor": "Wanda Ribeiro", "animal": "Brutus", "especie": "Cão", "servico": "Cirurgia", "valor": 510.0, "cidade": "Marília", "data": datetime(2026, 1, 25), "forma_pagamento": "Cartão"},
    {"tutor": "Xavier Pinto", "animal": "Bolinha", "especie": "Gato", "servico": "Banho e Tosa", "valor": 62.0, "cidade": "Pompeia", "data": datetime(2026, 1, 26), "forma_pagamento": "Dinheiro"},
    {"tutor": "Yasmin Correia", "animal": "Lassie", "especie": "Cão", "servico": "Consulta", "valor": 135.0, "cidade": "Ourinhos", "data": datetime(2026, 1, 27), "forma_pagamento": "Pix"},
    {"tutor": "Zilda Nascimento", "animal": "Simba", "especie": "Gato", "servico": "Vacina", "valor": 78.0, "cidade": "Assis", "data": datetime(2026, 1, 28), "forma_pagamento": "Cartão"},
    {"tutor": "André Moura", "animal": "Lady", "especie": "Cão", "servico": "Cirurgia", "valor": 420.0, "cidade": "Marília", "data": datetime(2026, 1, 29), "forma_pagamento": "Cartão"},
    {"tutor": "Beatriz Cunha", "animal": "Chico", "especie": "Coelho", "servico": "Banho e Tosa", "valor": 45.0, "cidade": "Pompeia", "data": datetime(2026, 1, 30), "forma_pagamento": "Dinheiro"},
    {"tutor": "Carlos Dias", "animal": "Pandora", "especie": "Gato", "servico": "Consulta", "valor": 105.0, "cidade": "Ourinhos", "data": datetime(2026, 2, 1), "forma_pagamento": "Pix"},
    {"tutor": "Diana Reis", "animal": "Trovão", "especie": "Cão", "servico": "Vacina", "valor": 97.0, "cidade": "Assis", "data": datetime(2026, 2, 2), "forma_pagamento": "Cartão"},
    {"tutor": "Eduardo Leal", "animal": "Pretinha", "especie": "Gato", "servico": "Cirurgia", "valor": 350.0, "cidade": "Marília", "data": datetime(2026, 2, 3), "forma_pagamento": "Cartão"},
    {"tutor": "Fernanda Vaz", "animal": "Lelê", "especie": "Coelho", "servico": "Banho e Tosa", "valor": 48.0, "cidade": "Pompeia", "data": datetime(2026, 2, 4), "forma_pagamento": "Dinheiro"},
    {"tutor": "Gustavo Pires", "animal": "Nego", "especie": "Cão", "servico": "Consulta", "valor": 118.0, "cidade": "Ourinhos", "data": datetime(2026, 2, 5), "forma_pagamento": "Pix"},
    {"tutor": "Helena Barbosa", "animal": "Duda", "especie": "Gato", "servico": "Vacina", "valor": 83.0, "cidade": "Assis", "data": datetime(2026, 2, 6), "forma_pagamento": "Cartão"},
    {"tutor": "Igor Fonseca", "animal": "Branquinha", "especie": "Cão", "servico": "Cirurgia", "valor": 560.0, "cidade": "Marília", "data": datetime(2026, 2, 7), "forma_pagamento": "Cartão"},
    {"tutor": "Juliana Macedo", "animal": "Flocos", "especie": "Gato", "servico": "Banho e Tosa", "valor": 58.0, "cidade": "Pompeia", "data": datetime(2026, 2, 8), "forma_pagamento": "Pix"},
    {"tutor": "Kleber Monteiro", "animal": "Hulk", "especie": "Cão", "servico": "Consulta", "valor": 145.0, "cidade": "Ourinhos", "data": datetime(2026, 2, 9), "forma_pagamento": "Cartão"},
    {"tutor": "Leticia Borges", "animal": "Pompom", "especie": "Coelho", "servico": "Vacina", "valor": 76.0, "cidade": "Assis", "data": datetime(2026, 2, 10), "forma_pagamento": "Dinheiro"},
    {"tutor": "Marcos Vieira", "animal": "Fera", "especie": "Cão", "servico": "Cirurgia", "valor": 490.0, "cidade": "Marília", "data": datetime(2026, 2, 11), "forma_pagamento": "Cartão"},
    {"tutor": "Nathalia Cruz", "animal": "Pingo", "especie": "Gato", "servico": "Banho e Tosa", "valor": 52.0, "cidade": "Pompeia", "data": datetime(2026, 2, 12), "forma_pagamento": "Pix"},
    {"tutor": "Otavio Mendes", "animal": "Caramelo", "especie": "Cão", "servico": "Consulta", "valor": 128.0, "cidade": "Ourinhos", "data": datetime(2026, 2, 13), "forma_pagamento": "Cartão"},
    {"tutor": "Patricia Assis", "animal": "Tigrão", "especie": "Gato", "servico": "Vacina", "valor": 91.0, "cidade": "Assis", "data": datetime(2026, 2, 14), "forma_pagamento": "Pix"},
    {"tutor": "Roberto Queiroz", "animal": "Floquinho", "especie": "Cão", "servico": "Cirurgia", "valor": 430.0, "cidade": "Marília", "data": datetime(2026, 2, 15), "forma_pagamento": "Cartão"},
    {"tutor": "Silvia Teixeira", "animal": "Missy", "especie": "Gato", "servico": "Banho e Tosa", "valor": 68.0, "cidade": "Pompeia", "data": datetime(2026, 2, 16), "forma_pagamento": "Dinheiro"},
    {"tutor": "Thiago Andrade", "animal": "Pantera", "especie": "Cão", "servico": "Consulta", "valor": 150.0, "cidade": "Ourinhos", "data": datetime(2026, 2, 17), "forma_pagamento": "Pix"},
    {"tutor": "Ubirajara Lima", "animal": "Gatinha", "especie": "Gato", "servico": "Vacina", "valor": 86.0, "cidade": "Assis", "data": datetime(2026, 2, 18), "forma_pagamento": "Cartão"},
    {"tutor": "Vera Campos", "animal": "Raio", "especie": "Cão", "servico": "Cirurgia", "valor": 580.0, "cidade": "Marília", "data": datetime(2026, 2, 19), "forma_pagamento": "Cartão"},
    {"tutor": "Wilson Souza", "animal": "Cookie", "especie": "Coelho", "servico": "Banho e Tosa", "valor": 42.0, "cidade": "Pompeia", "data": datetime(2026, 2, 20), "forma_pagamento": "Dinheiro"},
    {"tutor": "Ximena Rocha", "animal": "Trovador", "especie": "Cão", "servico": "Consulta", "valor": 122.0, "cidade": "Ourinhos", "data": datetime(2026, 2, 21), "forma_pagamento": "Cartão"},
    {"tutor": "Yuri Batista", "animal": "Nemo", "especie": "Gato", "servico": "Vacina", "valor": 94.0, "cidade": "Assis", "data": datetime(2026, 2, 22), "forma_pagamento": "Pix"}
]

colecao.insert_many(atendimentos)

InsertManyResult([ObjectId('69c33af2bf8e037fe2de887e'), ObjectId('69c33af2bf8e037fe2de887f'), ObjectId('69c33af2bf8e037fe2de8880'), ObjectId('69c33af2bf8e037fe2de8881'), ObjectId('69c33af2bf8e037fe2de8882'), ObjectId('69c33af2bf8e037fe2de8883'), ObjectId('69c33af2bf8e037fe2de8884'), ObjectId('69c33af2bf8e037fe2de8885'), ObjectId('69c33af2bf8e037fe2de8886'), ObjectId('69c33af2bf8e037fe2de8887'), ObjectId('69c33af2bf8e037fe2de8888'), ObjectId('69c33af2bf8e037fe2de8889'), ObjectId('69c33af2bf8e037fe2de888a'), ObjectId('69c33af2bf8e037fe2de888b'), ObjectId('69c33af2bf8e037fe2de888c'), ObjectId('69c33af2bf8e037fe2de888d'), ObjectId('69c33af2bf8e037fe2de888e'), ObjectId('69c33af2bf8e037fe2de888f'), ObjectId('69c33af2bf8e037fe2de8890'), ObjectId('69c33af2bf8e037fe2de8891'), ObjectId('69c33af2bf8e037fe2de8892'), ObjectId('69c33af2bf8e037fe2de8893'), ObjectId('69c33af2bf8e037fe2de8894'), ObjectId('69c33af2bf8e037fe2de8895'), ObjectId('69c33af2bf8e037fe2de8896'), ObjectId('69c33af2bf8e037fe2de8897'), ObjectId('69c33af2bf8e037fe2de8898'), ObjectId('69c33af2bf8e037fe2de8899'), ObjectId('69c33af2bf8e037fe2de889a'), ObjectId('69c33af2bf8e037fe2de889b'), ObjectId('69c33af2bf8e037fe2de889c'), ObjectId('69c33af2bf8e037fe2de889d'), ObjectId('69c33af2bf8e037fe2de889e'), ObjectId('69c33af2bf8e037fe2de889f'), ObjectId('69c33af2bf8e037fe2de88a0'), ObjectId('69c33af2bf8e037fe2de88a1'), ObjectId('69c33af2bf8e037fe2de88a2'), ObjectId('69c33af2bf8e037fe2de88a3'), ObjectId('69c33af2bf8e037fe2de88a4'), ObjectId('69c33af2bf8e037fe2de88a5'), ObjectId('69c33af2bf8e037fe2de88a6'), ObjectId('69c33af2bf8e037fe2de88a7'), ObjectId('69c33af2bf8e037fe2de88a8'), ObjectId('69c33af2bf8e037fe2de88a9'), ObjectId('69c33af2bf8e037fe2de88aa'), ObjectId('69c33af2bf8e037fe2de88ab'), ObjectId('69c33af2bf8e037fe2de88ac'), ObjectId('69c33af2bf8e037fe2de88ad'), ObjectId('69c33af2bf8e037fe2de88ae'), ObjectId('69c33af2bf8e037fe2de88af')], acknowledged=True)

In [36]:
atendimentos_filtrados = list(colecao.find({
    'valor': {'$gte': 90, '$lte': 200}
}))

display(atendimentos_filtrados[:3])

[{'_id': ObjectId('69c339efbf8e037fe2de8818'),
  'tutor': 'Ana Lima',
  'animal': 'Rex',
  'especie': 'Cão',
  'servico': 'Consulta',
  'valor': 120.0,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 1, 3, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c339efbf8e037fe2de881c'),
  'tutor': 'Elaine Costa',
  'animal': 'Bolt',
  'especie': 'Cão',
  'servico': 'Consulta',
  'valor': 130.0,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 1, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c339efbf8e037fe2de881d'),
  'tutor': 'Fabio Alves',
  'animal': 'Nina',
  'especie': 'Coelho',
  'servico': 'Vacina',
  'valor': 95.0,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 1, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

In [37]:
dados_mongo = list(colecao.find({
    'cidade': {'$in': ['Assis', 'Ourinhos', 'Pompeia', 'Marília']}
}))

display(dados_mongo[:3])

[{'_id': ObjectId('69c339efbf8e037fe2de8818'),
  'tutor': 'Ana Lima',
  'animal': 'Rex',
  'especie': 'Cão',
  'servico': 'Consulta',
  'valor': 120.0,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 1, 3, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c339efbf8e037fe2de8819'),
  'tutor': 'Bruno Souza',
  'animal': 'Mimi',
  'especie': 'Gato',
  'servico': 'Vacina',
  'valor': 85.0,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 1, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c339efbf8e037fe2de881a'),
  'tutor': 'Carla Nunes',
  'animal': 'Thor',
  'especie': 'Cão',
  'servico': 'Banho e Tosa',
  'valor': 70.0,
  'cidade': 'Marília',
  'data': datetime.datetime(2026, 1, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

In [38]:
df = pd.DataFrame(dados_mongo)
df['_id'] = df['_id'].astype(str)
df.head(3)

,_id,tutor,animal,especie,servico,valor,cidade,data,forma_pagamento
0,69c339efbf8e037fe2de8818,Ana Lima,Rex,Cão,Consulta,120.0,Ourinhos,2026-01-03,Pix
1,69c339efbf8e037fe2de8819,Bruno Souza,Mimi,Gato,Vacina,85.0,Assis,2026-01-04,Cartão
2,69c339efbf8e037fe2de881a,Carla Nunes,Thor,Cão,Banho e Tosa,70.0,Marília,2026-01-05,Dinheiro

In [39]:
print(df.isnull().sum())

_id                0
tutor              0
animal             0
especie            0
servico            0
valor              0
cidade             0
data               0
forma_pagamento    0
dtype: int64

In [40]:
faturamento_total = df['valor'].sum()
print(f"Faturamento Total: R$ {faturamento_total:.2f}")

Faturamento Total: R$ 27699.00

In [41]:
faturamento_por_cidade = df.groupby('cidade')['valor'].sum().sort_values(ascending=False)
faturamento_por_cidade

cidade
Marília     16200.0
Ourinhos     4929.0
Assis        3405.0
Pompeia      3165.0
Name: valor, dtype: float64

In [42]:
faturamento_por_servico = df.groupby('servico')['valor'].sum().sort_values(ascending=False)
faturamento_por_servico

servico
Cirurgia        17340.0
Consulta         4929.0
Vacina           3405.0
Banho e Tosa     2025.0
Name: valor, dtype: float64

In [43]:
ticket_medio_geral = df['valor'].mean()
print(f"Ticket Médio Geral: R$ {ticket_medio_geral:.2f}")

Ticket Médio Geral: R$ 184.66

In [44]:
ticket_medio_por_cidade = df.groupby('cidade')['valor'].mean().round(2)
ticket_medio_por_cidade

cidade
Assis        87.31
Marília     450.00
Ourinhos    126.38
Pompeia      87.92
Name: valor, dtype: float64

In [45]:
servico_mais_lucrativo = df.groupby('servico')['valor'].sum().idxmax()
print(f"Serviço mais lucrativo: {servico_mais_lucrativo}")

Serviço mais lucrativo: Cirurgia

In [46]:
cidade_maior_faturamento = df.groupby('cidade')['valor'].sum().idxmax()
print(f"Cidade com maior faturamento: {cidade_maior_faturamento}")

Cidade com maior faturamento: Marília

In [47]:
top_3 = df.nlargest(3, 'valor')[['tutor', 'animal', 'servico', 'valor', 'cidade']]
top_3

             tutor animal   servico  valor   cidade
14   Olivia Santos   Zeus  Cirurgia  600.0  Marília
64   Olivia Santos   Zeus  Cirurgia  600.0  Marília
114  Olivia Santos   Zeus  Cirurgia  600.0  Marília

In [48]:
top_3_lista = df.nlargest(3, 'valor')[['tutor', 'animal', 'servico', 'valor', 'cidade']].to_dict(orient='records')

relatorio = {
    'data_geracao': datetime.now(),
    'faturamento_total': float(faturamento_total),
    'faturamento_por_cidade': faturamento_por_cidade.to_dict(),
    'faturamento_por_servico': faturamento_por_servico.to_dict(),
    'ticket_medio_geral': round(float(ticket_medio_geral), 2),
    'ticket_medio_por_cidade': ticket_medio_por_cidade.to_dict(),
    'servico_mais_lucrativo': servico_mais_lucrativo,
    'cidade_maior_faturamento': cidade_maior_faturamento,
    'top_3_atendimentos': top_3_lista
}

display(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 25, 1, 31, 30, 869889),
 'faturamento_total': 27699.0,
 'faturamento_por_cidade': {'Marília': 16200.0,
  'Ourinhos': 4929.0,
  'Assis': 3405.0,
  'Pompeia': 3165.0},
 'faturamento_por_servico': {'Cirurgia': 17340.0,
  'Consulta': 4929.0,
  'Vacina': 3405.0,
  'Banho e Tosa': 2025.0},
 'ticket_medio_geral': 184.66,
 'ticket_medio_por_cidade': {'Assis': 87.31,
  'Marília': 450.0,
  'Ourinhos': 126.38,
  'Pompeia': 87.92},
 'servico_mais_lucrativo': 'Cirurgia',
 'cidade_maior_faturamento': 'Marília',
 'top_3_atendimentos': [{'tutor': 'Olivia Santos',
   'animal': 'Zeus',
   'servico': 'Cirurgia',
   'valor': 600.0,
   'cidade': 'Marília'},
  {'tutor': 'Olivia Santos',
   'animal': 'Zeus',
   'servico': 'Cirurgia',
   'valor': 600.0,
   'cidade': 'Marília'},
  {'tutor': 'Olivia Santos',
   'animal': 'Zeus',
   'servico': 'Cirurgia',
   'valor': 600.0,
   'cidade': 'Marília'}]}

In [49]:
colecao_relatorios = db['relatorios']
colecao_relatorios.insert_one(relatorio)

InsertOneResult(ObjectId('69c33af2bf8e037fe2de88b0'), acknowledged=True)

In [50]:
for r in colecao_relatorios.find():
    display(r)

{'_id': ObjectId('69c339efbf8e037fe2de884a'),
 'data_geracao': datetime.datetime(2026, 3, 25, 1, 27, 11, 768000),
 'faturamento_total': 9233.0,
 'faturamento_por_cidade': {'Marília': 5400.0,
  'Ourinhos': 1643.0,
  'Assis': 1135.0,
  'Pompeia': 1055.0},
 'faturamento_por_servico': {'Cirurgia': 5780.0,
  'Consulta': 1643.0,
  'Vacina': 1135.0,
  'Banho e Tosa': 675.0},
 'ticket_medio_geral': 184.66,
 'ticket_medio_por_cidade': {'Assis': 87.31,
  'Marília': 450.0,
  'Ourinhos': 126.38,
  'Pompeia': 87.92},
 'servico_mais_lucrativo': 'Cirurgia',
 'cidade_maior_faturamento': 'Marília',
 'top_3_atendimentos': [{'tutor': 'Olivia Santos',
   'animal': 'Zeus',
   'servico': 'Cirurgia',
   'valor': 600.0,
   'cidade': 'Marília'},
  {'tutor': 'Vera Campos',
   'animal': 'Raio',
   'servico': 'Cirurgia',
   'valor': 580.0,
   'cidade': 'Marília'},
  {'tutor': 'Igor Fonseca',
   'animal': 'Branquinha',
   'servico': 'Cirurgia',
   'valor': 560.0,
   'cidade': 'Marília'}]}

{'_id': ObjectId('69c33af2bf8e037fe2de88b0'),
 'data_geracao': datetime.datetime(2026, 3, 25, 1, 31, 30, 869000),
 'faturamento_total': 27699.0,
 'faturamento_por_cidade': {'Marília': 16200.0,
  'Ourinhos': 4929.0,
  'Assis': 3405.0,
  'Pompeia': 3165.0},
 'faturamento_por_servico': {'Cirurgia': 17340.0,
  'Consulta': 4929.0,
  'Vacina': 3405.0,
  'Banho e Tosa': 2025.0},
 'ticket_medio_geral': 184.66,
 'ticket_medio_por_cidade': {'Assis': 87.31,
  'Marília': 450.0,
  'Ourinhos': 126.38,
  'Pompeia': 87.92},
 'servico_mais_lucrativo': 'Cirurgia',
 'cidade_maior_faturamento': 'Marília',
 'top_3_atendimentos': [{'tutor': 'Olivia Santos',
   'animal': 'Zeus',
   'servico': 'Cirurgia',
   'valor': 600.0,
   'cidade': 'Marília'},
  {'tutor': 'Olivia Santos',
   'animal': 'Zeus',
   'servico': 'Cirurgia',
   'valor': 600.0,
   'cidade': 'Marília'},
  {'tutor': 'Olivia Santos',
   'animal': 'Zeus',
   'servico': 'Cirurgia',
   'valor': 600.0,
   'cidade': 'Marília'}]}